### ISSUE TITLE
Beginner Friendly Issue - Validate New Default Credentials

### ISSUE THREAD

**Issue by wimpywarlord** [wimpywarlord/AutoDoc#1]
🚫 DISCLAIMER 🚫 
Kindly don't consider this issue as an actual contribution towards your Hacktoberfest challenge, this is to only get you familiar with the concept of sending PRs.

Go through other issues and try to contribute to those. 

A good list of beginner-friendly issues can be found in the following links: 

https://github.com/wimpywarlord/Hacktober-Wimpy-Style/blob/main/Issues/issues.md

https://github.com/vinitshahdeo/Hacktoberfest2021

Hi,

👉  So I think you found this issue from the Beginner-friendly issues list, and you are just getting started with Open Source.

👉  This is a perfect opportunity to get your hand dirty, and not get overwhelmed at the same time. 

👉 I have deliberately introduced a bug into my website. 

💕 Problem 

The Default credentials for testing are currently set as `admin` and `admin`. 

![Screenshot_11](https://user-images.githubusercontent.com/41532804/135171512-0612a9b4-0902-4f42-b0bc-3f70177ced1b.png)

I want to change the default testing password to `Wimpy_is_so_cool@123`. 

Change the validation `Javascript` code and show correct credentials to the user on the login page. 

![Screenshot_10](https://user-images.githubusercontent.com/41532804/135171640-74eb5e86-3e5c-441f-bb18-62c549c351c1.png)

💕Assistance

It's under the `views` folder, inside the `login.ejs` file.

 💕How to contribute.
 
 Send a PR, and I review it. If it's up to the mark, I will approve it and merge it to the main codebase. 
 
 Learn how to send a PR [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

**Comment by rachana-singh27** [comment]
Hi @wimpywarlord  I wanted to work on this issue, can you please assign this to me? Also, is this issue included in hacktoberfest 2021?

**Comment by wimpywarlord** [comment]
Hi @rachana-singh27,

Yes, this is included. 

Sure go ahead and work on it and send your PR.

**Comment by satkar2001** [comment]
hi kshitij i have updated the new testing credentials in both line 172 i.e the <small> tag to and line 200 to validate in javascript.please merge my PR if its ok

**Comment by satkar2001** [comment]
@wimpywarlord
 hi kshitij i have updated the new testing credentials in both line 172 i.e the tag to and line 200 to validate in javascript.please merge my PR if its ok

**Comment by wimpywarlord** [comment]
The issue is assigned to @rachana-singh27 and her PR has been merged. The issue now stands closed.
